version: '3'

services:
  product-service:
    build: ./product
    volumes:
      - ./product:/usr/src/app
    ports:
    # 5001 on host machine to port onto port 80 of the container
      - 5001:80

  product-details-service:
    build: ./product-details
    volumes:
      - ./product-details:/usr/src/app
    ports:
      # 5002 on host machine to port onto port 80 of the container
      - 5002:80

  website:
    image:
      php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - product-service
      - product-details-service
